version: "3.8"
services:

  tracker-db:
    container_name: tracker-db
    image: mariadb:10.7
    ports:
      - "3401:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=tracker_db
    networks:
      - backend-network
    depends_on:
      product-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  product-db:
    container_name: product-db
    image: mariadb:10.7
    ports:
      - "3402:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=product_db
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  calendar-db:
    container_name: calendar-db
    image: mariadb:10.7
    ports:
      - "3403:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=calendar_db
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  shoppingList-db:
    container_name: shoppingList-db
    image: mariadb:10.7
    ports:
      - "3404:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=shoppingList_db
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  product-api:
    container_name: product-api
    image: golang:1.20-alpine
    working_dir: /app
    volumes:
      - ./backend/productApi:/app
    command: sh -c "go mod tidy && go build -o /tmp/main ./api/cmd/main.go && /tmp/main"
    ports:
      - "9402:9402"
    depends_on:
      product-db:
        condition: service_healthy
    networks:
      - backend-network

  calendar-api:
    container_name: calendar-api
    image: golang:1.20-alpine
    working_dir: /app
    volumes:
      - ./backend/calendarApi:/app
    command: sh -c "go mod tidy && go build -o /tmp/main ./api/cmd/main.go && /tmp/main"
    ports:
      - "9403:9403"
    depends_on:
      calendar-db:
        condition: service_healthy
    networks:
      - backend-network

  shoppingList-api:
    container_name: shoppingList-api
    image: golang:1.20-alpine
    working_dir: /app
    volumes:
      - ./backend/shoppingListApi:/app
    command: sh -c "go mod tidy && go build -o /tmp/main ./api/cmd/main.go && /tmp/main"
    ports:
      - "9404:9404"
    depends_on:
      shoppingList-db:
        condition: service_healthy
    networks:
      - backend-network

  tracker-api:
    container_name: tracker-api
    image: golang:1.20-alpine
    working_dir: /app
    volumes:
      - ./backend/tracker:/app
    command: sh -c "go mod tidy && go build -o /tmp/main ./api/cmd/main.go && /tmp/main"
    ports:
      - "9401:9401"
    depends_on:
      product-db:
        condition: service_healthy
      calendar-db:
        condition: service_healthy
      shoppingList-db:
        condition: service_healthy
      tracker-db:
        condition: service_healthy
      product-api:
        condition: service_started
      calendar-api:
        condition: service_started
      shoppingList-api:
        condition: service_started
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge