version: "3.8"

volumes:
  product-api:
    driver: local
  shoppinglist-api:
    driver: local
  calendar-api:
    driver: local
  tracker:
    driver: local
  frontend:
    driver: local

services:
  tracker-db:
    container_name: tracker-db
    image: mariadb:10.7
    ports:
      - "3401:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=tracker_db
    networks:
      - backend-network
    depends_on:
      - product-db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  product-db:
    container_name: product-db
    image: mariadb:10.7
    ports:
      - "3402:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=product_db
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  calendar-db:
    container_name: calendar-db
    image: mariadb:10.7
    ports:
      - "3403:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=calendar_db
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  shoppinglist-db:
    container_name: shoppinglist-db
    image: mariadb:10.7
    ports:
      - "3404:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=shoppingList_db
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  product-api:
    container_name: product-api
    restart: always
    build:
      context: ./backend/productApi
      dockerfile: Dockerfile
    volumes:
      - product-api:/var/lib/product-api/data
    ports:
      - "9402:9402"
    depends_on:
      - product-db
    networks:
      - backend-network

  calendar-api:
    container_name: calendar-api
    restart: always
    build:
      context: ./backend/calendarApi
      dockerfile: Dockerfile
    volumes:
      - calendar-api:/var/lib/calendar-api/data
    ports:
      - "9403:9403"
    depends_on:
      - calendar-db
    networks:
      - backend-network

  shoppinglist-api:
    container_name: shoppinglist-api
    restart: always
    build:
      context: ./backend/shoppingListApi
      dockerfile: Dockerfile
    volumes:
      - shoppinglist-api:/var/lib/shoppinglist-api/data
    ports:
      - "9404:9404"
    depends_on:
      - shoppinglist-db
    networks:
      - backend-network

  tracker-api:
    container_name: tracker-api
    restart: always
    build:
      context: ./backend/tracker
      dockerfile: Dockerfile
    volumes:
      - tracker:/var/lib/tracker/data
    ports:
      - "9401:9401"
    depends_on:
      - product-db
      - calendar-db
      - shoppinglist-db
      - tracker-db
      - product-api
      - calendar-api
      - shoppinglist-api
    networks:
      - backend-network
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/app
    ports:
      - "1420:1420"
    depends_on:
      - tracker-api
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge